LLM_API_KEY=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
MS_GRAPH_TENANT_ID=e2f55da3-7c96-442f-a150-ec6ac937cadf
MS_GRAPH_CLIENT_ID=56da8328-dac1-415b-8007-fb3d03c4cfb3
MS_GRAPH_CLIENT_SECRET=UUf8Q~KspWhRd8Bgf_~p5SC2Wt4jzpmSkc1Jmczc
