LLM_API_KEY=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
MS_GRAPH_TENANT_ID=e2f55da3-7c96-442f-a150-ec6ac937cadf
MS_GRAPH_CLIENT_ID=56da8328-dac1-415b-8007-fb3d03c4cfb3
MS_GRAPH_CLIENT_SECRET=UUf8Q~KspWhRd8Bgf_~p5SC2Wt4jzpmSkc1Jmczc
